language: objective-c
before_script:
    - brew update
    - brew unlink xctool
    - brew install -v --HEAD xctool
script:
    - xctool -workspace OpenMRS-iOS.xcworkspace/ -scheme OpenMRS-iOS test -sdk iphonesimulator -xcconfig TestBuild.xcconfig
osx_image: xcode611
